[package]
name = "AOC2019"
version = "0.1.0"
authors = ["Joshy Orndorff"]
edition = "2018"

[workspace]
members = [
  "day01",
  "day02",
]

[[bin]]
name = "day1"
path = "day1/src/main.rs"

[[bin]]
name = "day2"
path = "day2/src/main.rs"
